### ISSUE TITLE
Enforce TLS 1.2 in License Script and assign permissions in AAD App

### ISSUE THREAD

**Issue by harbinger85585** [Jannos-443/PRTG-M365#1]
Thank you for the great M365 licensing script.
Since a few days it wasn't working anymore for us, I had to enforce TLS1.2 with the following command at the beginning of the script:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Also the check for groups with assignments wasn't working anymore, I've had to assign the application permission Directory.ReadAll to the AAD App so the query would work again.

**Comment by Jannos-443** [comment]
Hello,

the permission thing was my fault, forgot to add "Group.Read.All" to the requirements because of the Group Based License check. You could try to remove "Directory.ReadAll".

I added the Tls1.2 part into the script :)

**Comment by harbinger85585** [comment]
Hi,

Thanks for adding the TLS part.
I've added the Group.Read.All permissions to the App, removed the Directory.Read.All and can confirm that it's working.
I think this closes the issue.
