### ISSUE TITLE
Error Loading Module

### ISSUE THREAD

**Issue by MatthewGeo** [Jannos-443/PRTG-M365#10]
Hi Jannos-443,

many thanks for they great PRTG scripts :)
I just tried the M365 Quarantain script, but i get this error:

Error Loading ExchangeOnlineManagement Powershell Module (Das angegebene Modul "ExchangeOnlineManagement" wurde nicht geladen, da in keinem Modulverzeichnis eine g�ltige Moduldatei gefunden wurde.)

Other Powershell scripts are working perfectly on the probe. This is the only one not working.

Do you know why and what to do?

Many thanks.

**Comment by ObiKaiKenobi** [comment]
Hi MatthewGeo,

It looks like the "Exchange Online PowerShell module" is missing on your PRTG-Server.

You can install the module with the following command: "Install-Module -Name ExchangeOnlineManagement"

See: https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exchange-online-powershell-module

Hope this helps.

KR Kai

**Comment by MatthewGeo** [comment]
Hi ObiKaiKenobi,

looks much better now - many thanks :)

Have a nice day.
