### ISSUE TITLE
sensor creates new free channel 

### ISSUE THREAD

**Issue by ymcnelly** [Jannos-443/PRTG-M365#3]
Hi.

Me again. I want to trigger a notification every time de free licenses drop below a certain point. But everytime the free amount changes, it creates a new channel. Can the script be changed so the channels stay the same?

**Comment by Jannos-443** [comment]
Hey, you should be able to just change the channel limit and it should not create any new channels after that.

Could you please recreate the sensor an try it again.

If it's not working could you make a screenshot and show the parameter you use.
