### ISSUE TITLE
displaying product name not string ID

### ISSUE THREAD

**Issue by SteveHGW** [Jannos-443/PRTG-M365#4]
Is it possible to display the product name and not the string ID of the SKUs related to this overview:
https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference

**Comment by Jannos-443** [comment]
Hey Steve,
the latest Version has an -FriendlyName Option.
I also added -IncludeName and -ExcludeName to filter on the friendlynames.

best regards
