### ISSUE TITLE
prepaidUnits calculation if low license count

### ISSUE THREAD

**Issue by rphlwnk** [Jannos-443/PRTG-M365#6]
Since Microsoft decided to array the **prepaidUnits** and move the actual value according to the licenseing state i got a "-" value on the free licence sensor and no total license count:

![image](https://user-images.githubusercontent.com/34039879/210532125-117b3161-897a-4fca-8655-82ed196f2275.png)

So if you have less than x amount of free licenses the **prepaidUnits** count is not unter **.enabled** instead it is moved to **.warning** or **.suspended** - see example below:

```
capabilityStatus : Enabled
consumedUnits    : 5
skuPartNumber    : STREAM
appliesTo        : User
prepaidUnits     : @{enabled=1000000; suspended=0; warning=0}

capabilityStatus : Enabled
consumedUnits    : 1100
skuPartNumber    : ENTERPRISEPACK
appliesTo        : User
prepaidUnits     : @{enabled=0; suspended=0; warning=1100}
```

It is a simple fix where you can add up enabled+warning+suspended on line 279

```
$NewLic.PrepaidUnitsEnabled = ($R.PrepaidUnits.enabled + $R.PrepaidUnits.warning + $R.PrepaidUnits.suspended)
```

![image](https://user-images.githubusercontent.com/34039879/210533210-eda2e0ca-a051-42f0-8982-7e8678ddb7c7.png)

**Comment by Jannos-443** [comment]
Hey rphlwnk,

good point, thank you.
I changed the line :)
