### ISSUE TITLE
SAML cert expiration

### ISSUE THREAD

**Issue by hhantelm** [Jannos-443/PRTG-M365#8]
I thought people might want to add their SAML certificate expirations to the monitor. I created a fork and pull request of that addition if you want to merge it into yours :)

**Comment by Jannos-443** [comment]
hey hhantelm,
very good idea, could you send me some example picture that I could add to the repo?
I currently have no option to test this.

Thank you :)

**Comment by hhantelm** [comment]
Rather than post a picture from our environment, I can provide a link to a blog that describes this setup process. The author provides step by step pictures of a SAML-based SSO. The certificate I am referring to is step 13 in this example.
https://www.c-sharpcorner.com/article/azure-ad-add-an-enterprise-application-configure-saml-sso-and-automate-user-p/

**Comment by Jannos-443** [comment]
okay I was able to test it with the following site: https://samltoolkit.azurewebsites.net/
Thank you for this Feature.
