### ISSUE TITLE
PRTG-M365-Licenses.ps1: GroupBasedLicenseError shows 0 while it should be 1

### ISSUE THREAD

**Issue by Sabbest313** [Jannos-443/PRTG-M365#9]
Hi,

I've setup the [PRTG-M365-Licenses.ps1](https://github.com/Jannos-443/PRTG-M365/blob/main/PRTG-M365-Licenses.ps1) script. I've purposely set 1 group to have licenses errors (14 users added with only 13 licenses present). The reported license count is correct, however the GroupBasedLicenseError still shows 0 instead of 1. 
I'm using the GroupBasedLicenseError wrong? As I see it it should return the number of groups that have license errors within the scope of the queried licenses.

**Comment by Jannos-443** [comment]
Hi,
did you see the license error in Azure AD itself?
Should exactly work as you described

**Comment by Sabbest313** [comment]
HI,

Yes, Azure AD does show the error yet PRTG doesn't (see attachments).

![AAD_group_error](https://user-images.githubusercontent.com/128400842/227545754-4ebe194f-44cd-4d07-8e18-a264d703ef99.png)
![PRTG_no_error](https://user-images.githubusercontent.com/128400842/227545768-9985b80b-9c5e-4b34-ab75-aa0dcc3abbb3.png)

**Comment by Jannos-443** [comment]
looks like Microsoft changed something in the Graph API, should now work again with the latest Version :)

**Comment by Sabbest313** [comment]
Updatet to the latest version, indeed it works now. Thanks a lot!
